### PR TITLE
ZugferdSettings: Give possitibility to let different tags have different number of decimals

### PR DESCRIPTION
**Pull request by danielmarschall**
Example usage:
`ZugferdSettings::setAmountDecimals(5, "ram:ChargeAmount");`

### CODE REVIEW

**Comment by horstoeko** [comment]
Hi @danielmarschall ,

thank for the PR.

Please write the code a little cleaner - use spaces for more Readability (for example):
  - wrong: ``$tagName???“”``
  - correct: ``$tagName ?? “”``

Please write the necessary tests for this, as your change is in a way a major customization

**Comment by danielmarschall** [comment]
Unfortunately I have no experience with PHPunit. GitHub shows thousands of lines and I don't know what exactly failed.

**Comment by danielmarschall** [comment]
Ok, I found the place:

$this->assertEquals(3, $property->getValue());

this testcase line makes no sense to me. The value of the property is an implementation detail in my opinion , hence I made it private.

**Comment by horstoeko** [comment]
> Ok, I found the place:
> 
> $this->assertEquals(3, $property->getValue());
> 
> this testcase line makes no sense to me. The value of the property is an implementation detail in my opinion , hence I made it private.

What doesn't make sense? Please look at this test completely.

**Comment by danielmarschall** [comment]
Yes, there is one line above, which I did read.

In my opinion only public methods should be checked. The inner workings of the class are irrelevant. It makes no difference if the class writes the value in an int array, string array, memcache, database, etc.

When I am home, I will fix the testcase the way you prefer it, though.

**Comment by horstoeko** [comment]
Hi @danielmarschall,

I will come up with something in this regard in the coming days. Please give me time, I have a family and a regular job and am only doing the project out of pure self-interest. Please forgive me for not being able to respond to all requests immediately. I will try to help you over time. Is that okay with you?

**Comment by danielmarschall** [comment]
Hello @horstoeko ,

of course it is okay! :-) Don't worry. I tend to send a lot of requests/issues/PRs when I am actively working on/with a project. But nothing is time-critical. Take your time. And I am happy to contribute in order to improve this project.

I have sent a commit which should fix all issues. Now waiting for the tests to pass.

**Comment by horstoeko** [comment]
Good morning @danielmarschall,

I have been thinking about a different solution. I came up with the following idea:

Extension of ZugferdSetting by a property “unitAmountDecimals” for the special formatting of unit prices:

```php
/**
 * The number of decimals for unit amount values
 *
 * @var integer
 */
protected static $unitAmountDecimals = 2;
```

Extension of ZugferdSetting with a property that specifies the paths to the properties that are to be formatted with a different digit count:

```php
/**
 * Node paths which present a unit amount. Used for special amount formatting. See unitAmountDecimals property.
 *
 * @var array
 */
protected static $unitAmountNodePaths = [
    '/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:IncludedSupplyChainTradeLineItem/ram:SpecifiedLineTradeAgreement/ram:GrossPriceProductTradePrice/ram:ChargeAmount',
    '/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:IncludedSupplyChainTradeLineItem/ram:SpecifiedLineTradeAgreement/ram:NetPriceProductTradePrice/ram:ChargeAmount',
];
```

Getters and setters are provided for both properties:

```php
/**
 * Returns a list of node paths which present the unit amounts
 *
 * @return array
 */
public static function getUnitAmountNodePaths(): array
{
    return static::$unitAmountNodePaths;
}
```

```php
/**
 * Set a list of node paths which present the unit amounts
 *
 * @param string[] $unitAmountNodePaths
 * @return void
 */
public static function setUnitAmountNodePaths(array $unitAmountNodePaths): void
{
    static::$unitAmountNodePaths = $unitAmountNodePaths;
}
```

Extension of the method ``serializeAmountType`` in class ``ZugferdTypesHandler``:

```php
/**
 * Serialize Anount type
 * The amounts will be serialized with a precission of 2 digits
 *
 * @param  XmlSerializationVisitor $visitor
 * @param  mixed                   $data
 * @param  array                   $type
 * @param  Context                 $context
 * @return DOMText|false
 */
public function serializeAmountType(XmlSerializationVisitor $visitor, $data, array $type, Context $context)
{
    if (in_array($visitor->getCurrentNode()->getNodePath(), ZugferdSettings::getUnitAmountNodePaths())) {
        $amountDecimals = ZugferdSettings::getUnitAmountDecimals();
    } else {
        $amountDecimals = ZugferdSettings::getAmountDecimals();
    }

    $node = $visitor->getDocument()->createTextNode(
        number_format(
            $data->value(),
            $amountDecimals,
            ZugferdSettings::getDecimalSeparator(),
            ZugferdSettings::getThousandsSeparator()
        )
    );

    if ($data->getCurrencyID() != null) {
        $attr = $visitor->getDocument()->createAttribute("currencyID");
        $attr->value = $data->getCurrencyID();
        $visitor->getCurrentNode()->appendChild($attr);
    }

    return $node;
}
```

What do you think of this solution? I have prototyped it once and find it a more charming solution, as it does not break the previous implementation as much as your proposed solution. Please give me your feedback.

**Comment by danielmarschall** [comment]
Hello @horstoeko 

thank you for the fast reply. Please give me a bit time to look at your proposal.

Just a quick question upfront: Why do you think my implementation breaks stuff? I took care that it does not break anything. All testcases now pass and due to the optional parameters in the getter/setters, existing implementations are not disturbed. The only thing where implementations could **_theoretically_** break is if someone accesses the protected methods using reflection - but why would **_anybody_** do that (except for the internal testcases) if they can simply use the getters/setters as written in the documentation?

**Comment by danielmarschall** [comment]
Hello @horstoeko 

Ok, here is my opinion/feedback:

**_What I do like:_**

- You use `$visitor->getCurrentNode()->getNodePath()` instead of `$visitor->getCurrentNode()->tagName`. This identifies the attribute much more explicit, and hence it allows things like gross and net prices being handled separate from each other.

- By using `setUnitAmountDecimals()`, the developer does not need to care about the name or path of the node. It allows the specification to change names (for example, if a future would theoretically rename the field "CurrencyAmount" instead of "ChargeAmount", then only the zugferd lib would need to change, and not the developer's code).

**_What I don't like:_**

- With my solution, it is possible to change the amount of decimals of anything. So, you can give unit prices 5 decimals, tax sums 3 decimals, grand total 2 decimals, etc. HOWEVER, it looks like everything except the single-unit-price only allows 2 decimals per definition, so we should be fine?? (I need to look at the schematrons/rules to see if this is true)

- In my solution, I also applied the decimal handling for percentages and quanitites. Your solution will most likely not contain that. I could imagine that quantities might need more than 2 decimals in some use-cases. For example, high-valued goods like spirits in the beverage market, or gold, where there is a big difference between 0.01 grams and 0.001 grams.

What do you think?

**Comment by horstoeko** [comment]
Hi @danielmarschall,

thanks for your feedback.

 First of all (and please don't misunderstand me): I hope that we don't turn this topic into a never-ending story... :-)
 
> With my solution, it is possible to change the amount of decimals of anything. So, you can give unit prices 5 decimals, tax sums 3 decimals, grand total 2 decimals, etc. HOWEVER, it looks like everything except the single-unit-price only allows 2 decimals per definition, so we should be fine?? (**_TODO for me:_** I need to look at the schematrons/rules to see if this is true)

I think that only the individual prices with a digit count >2 should be taken into account. As far as I know, everything else violates the validation regulations.

> In my solution, I also applied the decimal handling for percentages and quanitites. 

I didn't see that... Maybe it was to late yesterday??

It would also be conceivable to offer a mapping from the NodePath to a digit. Then you are at least freer. But relying only on "chargeAmount" (as it probably was in your implementation) is absolutely wrong in my opinion. I think it is better to clarify this at XML path level.

**Comment by danielmarschall** [comment]
Hello @horstoeko 

> First of all (and please don't misunderstand me): I hope that we don't turn this topic into a never-ending story... :-)

Sure :-) But it's good to see different implementations and making the best, because once it is published, developers will rely on the methods of never changing again. But I'll try to make it as fast/easy as possible. Thanks for your patience.

> I think that only the individual prices with a digit count >2 should be taken into account. As far as I know, everything else violates the validation regulations.

Yes, this is also my theory. But I want to look at the rules again to verify that this is true, that everything except single-unit-prices enforces 2 digits. (TODO for me)

> It would also be conceivable to offer a mapping from the NodePath to a digit. Then you are at least freer. But relying only on "chargeAmount" (as it probably was in your implementation) is absolutely wrong in my opinion. I think it is better to clarify this at XML path level.

Yes, full path is better than node name.


I'll reply soon when I have fulfilled my 2 TODOs (1st check if 2-digit is enforced on all other fields,  and 2nd to check if there are different quantities and percentages in the schema which might need separate digit handling)

**Comment by danielmarschall** [comment]
Ok, I think I found all the places where quantities, percentages and amounts are used in the library. The code is very complex, and I am not sure if I understood it correctly... here is what I found:

```
getPercentType used in:
- ram\TradePaymentDiscountTermsType\CalculationPercent
- ram\TradeTaxType\RateApplicablePercent
- ram\TradeAllowanceChargeType\CalculationPercent

getQuantityType used in:
- ram\TradeAllowanceChargeType\BasisQuantity
- ram\ReferencedProductType\UnitQuantity
- ram\TradePriceType\BasisQuantity

getAmountType used in:
- ram\TradePaymentDiscountTermsType\BasisAmount
- ram\TradePaymentDiscountTermsType\ActualDiscountAmount
- ram\TradeTaxType\CalculatedAmount
- ram\TradeTaxType\BasisAmount
- ram\TradeTaxType\LineTotalBasisAmount
- ram\TradeTaxType\AllowanceChargeBasisAmount
- ram\TradeAllowanceChargeType\BasisAmount
- ram\TradeAllowanceChargeType\ActualAmount
- ram\LogisticsServiceChargeType\AppliedAmount
- ram\TradeSettlementHeaderMonetarySummationType\LineTotalAmount
- ram\TradeSettlementHeaderMonetarySummationType\ChargeTotalAmount
- ram\TradeSettlementHeaderMonetarySummationType\AllowanceTotalAmount
- ram\TradeSettlementHeaderMonetarySummationType\TaxBasisTotalAmount
- ram\TradeSettlementHeaderMonetarySummationType\TaxTotalAmount
- ram\TradeSettlementHeaderMonetarySummationType\RoundingAmount
- ram\TradeSettlementHeaderMonetarySummationType\GrandTotalAmount
- ram\TradeSettlementHeaderMonetarySummationType\TotalPrepaidAmount
- ram\TradeSettlementHeaderMonetarySummationType\DuePayableAmount
- ram\TradePriceType\ChargeAmount
- ram\TradeSettlementLineMonetarySummationType\LineTotalAmount
- ram\TradeSettlementLineMonetarySummationType\TotalAllowanceChargeAmount
```

Searching for the word "decimals" in the XSL* files gave the following result:

```
[BR-DEC-01]-The allowed maximum number of decimals for the Document level allowance amount (BT-92) is 2.
[BR-DEC-02]-The allowed maximum number of decimals for the Document level allowance base amount (BT-93) is 2.
[BR-DEC-05]-The allowed maximum number of decimals for the Document level charge amount (BT-99) is 2.
[BR-DEC-06]-The allowed maximum number of decimals for the Document level charge base amount (BT-100) is 2.
[BR-DEC-09]-The allowed maximum number of decimals for the Sum of Invoice line net amount (BT-106) is 2.
[BR-DEC-10]-The allowed maximum number of decimals for the Sum of allowanced on document level (BT-107) is 2.
[BR-DEC-11]-The allowed maximum number of decimals for the Sum of charges on document level (BT-108) is 2.
[BR-DEC-12]-The allowed maximum number of decimals for the Invoice total amount without VAT (BT-109) is 2.
[BR-DEC-13]-The allowed maximum number of decimals for the Invoice total VAT amount (BT-110) is 2.
[BR-DEC-14]-The allowed maximum number of decimals for the Invoice total amount with VAT (BT-112) is 2.
[BR-DEC-15]-The allowed maximum number of decimals for the Invoice total VAT amount in accounting currency (BT-111) is 2.
[BR-DEC-16]-The allowed maximum number of decimals for the Paid amount (BT-113) is 2. -- yes, the XSLT shows that it means PRE-paid
[BR-DEC-17] The allowed maximum number of decimals for the Rounding amount (BT-114) is 2.
[BR-DEC-18]-The allowed maximum number of decimals for the Amount due for payment (BT-115) is 2.
[BR-DEC-19]-The allowed maximum number of decimals for the VAT category taxable amount (BT-116) is 2.
[BR-DEC-20]-The allowed maximum number of decimals for the VAT category tax amount (BT-117) is 2.
[BR-DEC-23]-The allowed maximum number of decimals for the Invoice line net amount (BT-131) is 2.
[BR-DEC-24]-The allowed maximum number of decimals for the Invoice line allowance amount (BT-136) is 2.
[BR-DEC-25]-The allowed maximum number of decimals for the Invoice line allowance base amount (BT-137) is 2.
[BR-DEC-27]-The allowed maximum number of decimals for the Invoice line charge amount (BT-141) is 2.
[BR-DEC-28]-The allowed maximum number of decimals for the Invoice line charge base amount (BT-142) is 2.
[BR-CO-17]-VAT category tax amount (BT-117) = VAT category taxable amount (BT-116) x (VAT category rate (BT-119) / 100), rounded to two decimals.
```

First of all: We see that the rules all contain problems with amounts. Never with quantities or percentages. So it looks like these can have any number of decimals. So if that's true then we should be fine leaving `ZugferdSettings.setQuantityDecimals()` and `ZugferdSettings.setPercentageDecimals()` as they are.

I struggled with matching the BR-DEC-* rules with the getAmountType() findings... so I am not 100% sure if the theory is true that all amount decimals need to be 2 decimals, except for the single-unit-prices. Maybe you can look over these rules very quick. I think your proposal with `ZugferdSettings.setUnitAmountDecimals()` should be good then.

**Comment by horstoeko** [comment]
Hi @danielmarschall,

Find. Thank you for the analysis. So I think we can close this PR and I implement my own solution. I will make a new PR and will add you as a reviewer.  Would this okay for you?

Best regards.

**Comment by danielmarschall** [comment]
Yes, sounds good! Thank you

**Pull request closed without merging**
