### PR TITLE
addDocumentPaymentMeanToDirectDebit() now contains $creditorReferenceID parameter

### PR DESCRIPTION
**Pull request by danielmarschall**
Fixes https://github.com/horstoeko/zugferd/issues/53

### CODE REVIEW

**Comment by horstoeko** [comment]
Hi @danielmarschall,

nice... :-) Since your customization is a breaking change, I would like to mark the second parameter as “optional” - something like this:

```php
addDocumentPaymentMeanToDirectDebit(string $buyerIban, ?string $creditorReferenceID = null)
```

Could you kindly implement it like this?

**Comment by danielmarschall** [comment]
Fixed! Thanks for the hint

**Comment by horstoeko** [comment]
Hi @danielmarschall,

That's almost it... :-)

It should be

```php
public function addDocumentPaymentMeanToDirectDebit(string $buyerIban, ?string $creditorReferenceID = null): ZugferdDocumentBuilder
```

but not

```php
public function addDocumentPaymentMeanToDirectDebit(string $buyerIban, string $creditorReferenceID=null): ZugferdDocumentBuilder
```

You forgot the question mark in front of the type declaration. It is also easier to read if you insert a space before and after the ``=``. I know I'm fussy... :-)

**Comment by danielmarschall** [comment]
Done :-)

I also introduced another change to avoid hardcoded strings for payment means. It allows people to better understand what the number means, by hovering over the constant (IDE assumed ofc). What do you think?

**Comment by horstoeko** [comment]
Hi @danielmarschall,

that looks good... Merging....

**Pull request merged**
