### PR TITLE
adding backed enums for codelists

### PR DESCRIPTION
**Pull request by mokraemer**
Adding the backed enums in a new namespace, keeping the original names.

### CODE REVIEW

**Comment by horstoeko** [comment]
@mokraemer,

It is as I suspected: The builds for PHP < 8.1 do not go through. I can't merge the PR now.

**Comment by mokraemer** [comment]
I see, I don't know this feature. The enums (classes) are optional and not integrated in your code, which would be the step if enums are used instead of strings.

**Comment by horstoeko** [comment]
Hi,

> I see, I don't know this feature. The enums (classes) are optional and not integrated in your code

I am doing a code linting - that's why it was recognized as an error in the PHP version <= 8.0

> which would be the step if enums are used instead of strings.

I would have to discontinue PHP versions <= 8.0, which would probably be rather unfavorable in the current situation... ;-)

**Comment by horstoeko** [comment]
Hi @mokraemer,

I have found a solution to check and merge the PR. But there was at least one error in the code that I had to fix (ZugferdPaymentMeans) - there was a case of type String, which I removed. But nevertheless - good work, for which I would like to thank you. However, I have to put the matter on hold for now, as other build processes are still running on errors.

Kind reards

**Comment by mokraemer** [comment]
great.

**Pull request merged**
